name: Release

on:
  release:
    types: [created]

jobs:
  release-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          cd ./js
          npm ci
          npm run build
      - name: deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          run: netlify deploy --dir=./js/dist --prod
